dist: trusty
compiler: gcc
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-7 && CXX=g++-7
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - cmake --build .
